/control/verbose 0
/run/verbose 0
/tracking/verbose 0

/det/dopant Cd
/run/initialize

/gen/mode mono
/gen/particle neutron
/gen/monoEnergy 10 keV
/gen/isotropic true
/gen/randomizePos true

/analysis/neutronLifetimeFile neutron_lifetime_Cd.txt

/analysis/writeCaptureGammas true
/analysis/captureGammaFile capture_gammas_Cd.txt
/analysis/captureSummaryFile capture_summary_Cd.txt

/run/beamOn 1000000
